"""Schema definitions for all data sources.

These schemas define the structure of data loaded into the data warehouse.
Adjust field names and types to match your actual JSON data structure.
"""

# Generic score/log schema - adjust field names to match your JSON structure
sagemaker_schema = {
    # Source metadata
    "source_file": {"data_type": "text"},
    "request_id": {"data_type": "text"},
    "flow_indication": {"data_type": "text"},
    "flow_detected": {"data_type": "text"},
    "record_id": {"data_type": "bigint"},
    "amount": {"data_type": "text"},
    "record_date": {"data_type": "timestamp"},
    # Request/input fields - adjust these to match your JSON structure
    "channel": {"data_type": "text"},
    "is_existing": {"data_type": "text"},
    "label": {"data_type": "text"},
    "status_1": {"data_type": "text"},
    "status_2": {"data_type": "text"},
    "status_3": {"data_type": "text"},
    "report_available": {"data_type": "text"},
    "type": {"data_type": "text"},
    "provider_name": {"data_type": "text"},
    "first_decision": {"data_type": "text"},
    "max_value": {"data_type": "text"},
    "last_status": {"data_type": "text"},
    "address_state": {"data_type": "text"},
    "address_region": {"data_type": "text"},
    # Entity fields - adjust these to match your JSON structure
    "email": {"data_type": "text"},
    "phone": {"data_type": "text"},
    "date_of_birth": {"data_type": "text"},
    "entity_address_state": {"data_type": "text"},
    "entity_address_region": {"data_type": "text"},
    "entity_status_1": {"data_type": "text"},
    "entity_status_2": {"data_type": "text"},
    "entity_status_3": {"data_type": "text"},
    # External data source fields (e.g., credit bureau, API responses) - adjust to match your data
    "external_source_1_id": {"data_type": "text"},
    "external_source_1_label": {"data_type": "text"},
    "external_source_1_current_value": {"data_type": "text"},
    "external_source_1_max_value": {"data_type": "text"},
    "external_source_1_count": {"data_type": "text"},
    "external_source_1_outstanding": {"data_type": "text"},
    "external_source_2_id": {"data_type": "text"},
    "external_source_2_label": {"data_type": "text"},
    "external_source_2_current_value": {"data_type": "text"},
    "external_source_2_max_value": {"data_type": "text"},
    "external_source_2_count": {"data_type": "text"},
    "external_source_2_outstanding": {"data_type": "text"},
    # Model/algorithm output fields
    "model_name": {"data_type": "text"},
    "score": {"data_type": "double"},
    "format_type": {"data_type": "text"},
    "model_path": {"data_type": "text"},
    # DLT internal fields
    "_dlt_id": {"data_type": "text"},
    "_dlt_load_id": {"data_type": "text"},
}

# Generic policy/decision output schema - adjust field names to match your JSON structure
policy_schema = {
    # Base fields
    "source_file": {"data_type": "text"},
    "request_id": {"data_type": "text"},
    "record_id": {"data_type": "bigint"},
    "record_date": {"data_type": "timestamp"},
    "product_flow": {"data_type": "text"},
    "model_name": {"data_type": "text"},
    # Decision/policy output fields - adjust these to match your JSON structure
    "error": {"data_type": "text"},
    "exec_status_prod_code": {"data_type": "text"},
    "format_version": {"data_type": "text"},
    "product_code": {"data_type": "text"},
    "count": {"data_type": "bigint"},
    "exec_status_label_grouping": {"data_type": "text"},
    "label": {"data_type": "text"},
    "exec_status_age": {"data_type": "text"},
    "age_decision": {"data_type": "text"},
    "age": {"data_type": "bigint"},
    "reason_code_age": {"data_type": "text"},
    "exec_status_external_check": {"data_type": "text"},
    "external_check_result": {"data_type": "text"},
    "external_status": {"data_type": "text"},
    "exec_status_max_value": {"data_type": "text"},
    "external_label": {"data_type": "text"},
    "scoring_label": {"data_type": "double"},
    "decision": {"data_type": "double"},
    "exec_status_location_decline": {"data_type": "text"},
    "location": {"data_type": "text"},
    "location_decision": {"data_type": "text"},
    "location_decline_msg": {"data_type": "text"},
    "exec_status_existing_account": {"data_type": "text"},
    "state_decline_msg": {"data_type": "text"},
    "state_decision": {"data_type": "text"},
    "exec_status_scorecard_limits": {"data_type": "text"},
    "score_decision": {"data_type": "text"},
    "credit_score": {"data_type": "double"},
    "risk_score": {"data_type": "double"},
    "exec_status_email_similarity": {"data_type": "text"},
    "email_similarity_msg": {"data_type": "text"},
    "email_decision_code": {"data_type": "text"},
    "email_score": {"data_type": "double"},
    "reason_code": {"data_type": "text"},
    "exec_status_early_exit": {"data_type": "text"},
    "early_exit": {"data_type": "text"},
    "days_to_exit": {"data_type": "bigint"},
    "exec_status_no_data_decline": {"data_type": "text"},
    "no_data": {"data_type": "text"},
    "no_data_decline_msg": {"data_type": "text"},
    "exec_status_external_abtest": {"data_type": "text"},
    "external_score_decision": {"data_type": "text"},
    "assigned_external": {"data_type": "text"},
    "exec_status_early_exit_limit": {"data_type": "text"},
    "exec_status_offer_2wks": {"data_type": "text"},
    "exec_status_offer_1m": {"data_type": "text"},
    "final_decision": {"data_type": "text"},
    "exec_status_resp_format": {"data_type": "text"},
    # DLT internal fields
    "_dlt_id": {"data_type": "text"},
    "_dlt_load_id": {"data_type": "text"},
}
